python_library(
    sources=['**/*.py', '!test/', '!container/'],
    dependencies=[
        'lib/spack/external',
        'lib/spack/external/archspec',
        'lib/spack/external/jsonschema',
        'lib/spack/llnl',
        'lib/spack/spack/container:lib',
    ]
)
