python_library(
    sources=['**/*.py', '!test/**'],
    dependencies=[
        'lib/spack/external',
        'lib/spack/external/archspec',
        'lib/spack/external/jsonschema',
        'lib/spack/llnl',
    ]
)
