#!/bin/sh
#
# Copyright 2013-2021 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

#
# Spack compiler wrapper script.
#
# Compiler commands go through this compiler wrapper in Spack builds.
# The compiler wrapper is a thin layer around the standard compilers.
# It enables several key pieces of functionality:
#
# 1. It allows Spack to swap compilers into and out of builds easily.
# 2. It adds several options to the compile line so that spack
#    packages can find their dependencies at build time and run time:
#      -I and/or -isystem arguments for dependency /include directories.
#      -L                 arguments for dependency /lib directories.
#      -Wl,-rpath         arguments for dependency /lib directories.
#

# Error and exit if any undefined variable is dereferenced.
set -u

# This is a newline-delimited string of environment variable names that need to
# be set before the script runs. They are set by routines in
# spack.build_environment as part of the package installation process.
readonly parameters="\
SPACK_ENV_PATH
SPACK_DEBUG_LOG_DIR
SPACK_DEBUG_LOG_ID
SPACK_COMPILER_SPEC
SPACK_CC_RPATH_ARG
SPACK_CXX_RPATH_ARG
SPACK_F77_RPATH_ARG
SPACK_FC_RPATH_ARG
SPACK_TARGET_ARGS
SPACK_DTAGS_TO_ADD
SPACK_DTAGS_TO_STRIP
SPACK_LINKER_ARG
SPACK_SHORT_SPEC
SPACK_SYSTEM_DIRS"

# Optional parameters that aren't required to be set

# Boolean (true/false/custom) if we want to add debug flags
# SPACK_ADD_DEBUG_FLAGS

# If a custom flag is requested, it will be defined
# SPACK_DEBUG_FLAGS

# The compiler input variables are checked for sanity later:
#   SPACK_CC, SPACK_CXX, SPACK_F77, SPACK_FC
# The default compiler flags are passed from these variables:
#   SPACK_CFLAGS, SPACK_CXXFLAGS, SPACK_FFLAGS,
#   SPACK_LDFLAGS, SPACK_LDLIBS
# Debug env var is optional; set to "TRUE" for debug logging:
#   SPACK_DEBUG
# Test command is used to unit test the compiler script.
#   SPACK_TEST_COMMAND

# Print a message to stderr and exit with status 1.
die() {
    echo "ERROR: $1" >&2
    exit 1
}

check_IFS() {
    must_be="$1"
    if [ "$IFS" != "$must_be" ]; then
        die "\$IFS must be '$must_be', but was '$IFS'."
    fi
}

# Execute awk with the locale set to reliably process pathnames.
path_safe_awk() {
    # Quoted from an informative section of
    # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/awk.html:
    # > When using awk to process pathnames, it is recommended that LC_ALL, or
    #   at least LC_CTYPE and LC_COLLATE, are set to POSIX or C in the
    #   environment, since pathnames can contain byte sequences that do not form
    #   valid characters in some locales, in which case the utility's behavior
    #   would be undefined. In the POSIX locale each byte is a valid single-byte
    #   character, and therefore this problem is avoided.
    LC_ALL=C awk "$@"
}

# Perform several types of path normalization on the first argument, which is
# then split by $IFS (which must be set to the value ':'):
# - remove trailing directory slashes,
# - remove empty strings,
# - remove repeated paths.
canonicalize_paths() {
    # $1 is split according to $IFS, which is expected to be ':'.
    check_IFS ':'
    for dir in $1; do
        # Ignore empty directory paths.
        if [ -z "$dir" ]; then
            continue
        fi
        # Remove any trailing slash.
        printf '%s:' "${dir%/}"
        # Remove repeated entries, without reordering the entries.
    done | path_safe_awk 'BEGIN { RS = ":"; ORS = ":" }; $0 && !seen[$0]++'
}

# Test whether a path $1 is equal to any entry of $2.
path_contained_in_nonrecursive() {
    path_to_check="$1"
    # $2/$directory_list are split according to $IFS, which may be arbitrary but
    # is likely ':'.
    directory_list="$2"
    for dir_to_test in $directory_list; do
        # We strip any trailing slashes from either argument.
        if [ "${path_to_check%/}" -ef "${dir_to_test%/}" ]; then
            return 0
        fi
    done
    return 1
}

# Remove entries of $1 which are contained in $2.
filter_out_paths_from_another_set_of_paths() {
    candidate_paths="$1"
    paths_to_avoid="$2"
    # We output paths using the ':' separator, so we want to assume the same for
    # our input arguments to make it easier to follow.
    check_IFS ':'
    for candidate in $candidate_paths; do
        if ! path_contained_in_nonrecursive "$candidate" "$paths_to_avoid"; then
            printf '%s:' "$candidate"
        fi
    done
}

# Ignore the arguments, do nothing, and return successfully.
_() {
    return 0
}

# Exit with error if the parameter given by the name in $1 is unset or empty.
check_param_is_set() {
    param_name="$1"
    eval "_ \${${param_name}:?Spack compiler must be run from Spack! Input '$param_name' is missing.}"
}

# SPACK_SYSTEM_DIRS is delimited by :
readonly SPACK_SYSTEM_DIRS="$(IFS=':' canonicalize_paths "$SPACK_SYSTEM_DIRS")"

## Ensure all required parameters are set.
for param in $parameters; do
    check_param_is_set "$param"
done

## Check if optional parameters are defined.

# Define true/false/custom variables we can use in parameter expansions.
readonly True='true'
readonly False='false'
readonly Custom='custom'

# Determine whether $1 is equal to $True, $False, or $Custom.
is_valid_tribool() {
    readonly value="$1"
    [ "$value" = "$True" -o "$value" = "$False" -o "$value" = "$Custom" ]
}

# If we aren't asking for debug flags, don't add them.
_ ${SPACK_ADD_DEBUG_FLAGS:=$False}
export SPACK_ADD_DEBUG_FLAGS

if ! is_valid_tribool "$SPACK_ADD_DEBUG_FLAGS"; then
    die "\$SPACK_ADD_DEBUG_FLAGS, if defined, must be one of '$True' '$False', or '$Custom'."
fi

# Figure out the type of compiler, the language, and the mode so that
# the compiler script knows what to do.
#
# Possible languages are C, C++, Fortran 77, and Fortran 90.
# 'command' is set based on the input command to $SPACK_[CC|CXX|F77|F90]
#
# 'mode' is set to one of:
#    vcheck  version check
#    cpp     preprocess
#    cc      compile
#    as      assemble
#    ld      link
#    ccld    compile & link

command="${0##*/}"
case "$command" in
    cpp)
        mode=cpp
        debug_flags='-g'
        ;;
    cc|c89|c99|gcc|clang|armclang|icc|icx|pgcc|nvc|xlc|xlc_r|fcc)
        command="$SPACK_CC"
        language='C'
        comp='CC'
        lang_flags='C'
        debug_flags='-g'
        ;;
    c++|CC|g++|clang++|armclang++|icpc|icpx|pgc++|nvc++|xlc++|xlc++_r|FCC)
        command="$SPACK_CXX"
        language='C++'
        comp='CXX'
        lang_flags='CXX'
        debug_flags='-g'
        ;;
    ftn|f90|fc|f95|gfortran|flang|armflang|ifort|ifx|pgfortran|nvfortran|xlf90|xlf90_r|nagfor|frt)
        command="$SPACK_FC"
        language='Fortran 90'
        comp='FC'
        lang_flags='F'
        debug_flags='-g'
        ;;
    f77|xlf|xlf_r|pgf77)
        command="$SPACK_F77"
        language='Fortran 77'
        comp='F77'
        lang_flags='F'
        debug_flags='-g'
        ;;
    ld|ld.gold|ld.lld)
        mode='ld'
        ;;
    *)
        # Check that at least one of the known commands was actually selected,
        # otherwise we don't know what to execute.
        die "Unknown command '$command' selected. Compiler was: $SPACK_COMPILER_SPEC."
        ;;
esac
_ ${comp:='CC'}
_ ${lang_flags:=''}

# If any of the arguments below are present, then the mode is vcheck.
# In vcheck mode, nothing is added in terms of extra search paths or
# libraries.
case "${mode:-}" in
    ''|ld)
        for arg; do
            case "$arg" in
                -v|-V|--version|-dumpversion)
                    mode='vcheck'
                    break
                    ;;
            esac
        done
        ;;
esac

# Finish setting up the mode.
if [ -z "${mode:-}" ]; then
    mode='ccld'
    for arg; do
        case "$arg" in
            -E)
                mode='cpp'
                break
                ;;
            -S)
                mode='as'
                break
                ;;
            -c)
                mode='cc'
                break
                ;;
        esac
    done
fi

# Set up rpath variable according to language.
eval "readonly rpath=\$SPACK_${comp}_RPATH_ARG"

_ ${SPACK_TEST_COMMAND:=''}
# Dump the mode and exit if the command is dump-mode.
if [ "$SPACK_TEST_COMMAND" = 'dump-mode' ]; then
    echo "$mode"
    exit
fi

# Filter '.' and Spack environment directories out of $PATH so that this script
# doesn't just call itself.
readonly env_path="$(IFS=':' canonicalize_paths "$PATH")"
readonly spack_env_path="$(IFS=':' canonicalize_paths "$SPACK_ENV_PATH")"
readonly filtered_path="$(IFS=':' filter_out_paths_from_another_set_of_paths "$env_path" "$spack_env_path")"
# Remove the trailing ':' before putting it back in $PATH.
PATH="${filtered_path%:}"

if [ "$mode" = 'vcheck' ]; then
    exec "$command" "$@"
fi

# Darwin's linker has a -r argument that merges object files together.
# It doesn't work with -rpath, so $add_rpaths controls whether they are added.
case "$mode" in
    ld|ccld)
        case "$SPACK_SHORT_SPEC" in
            *darwin*)
                for arg; do
                    case "${arg}~${mode}" in
                        -r~ld|-r~ccld|-Wl,-r~ccld)
                            add_rpaths=$False
                            break
                            ;;
                    esac
                done
                ;;
        esac
        ;;
esac
_ ${add_rpaths:=$True}

# Save original command for debug logging
readonly input_command="$*"

readonly awk_args_script='
BEGIN {
    # Split SPACK_SYSTEM_DIRS into an array of directory paths.
    gsub(/^:|:$/, "", ENVIRON["SPACK_SYSTEM_DIRS"])
    split(ENVIRON["SPACK_SYSTEM_DIRS"], spack_system_dirs, ":")
    # Remove any trailing slashes.
    for (system_dir in spack_system_dirs) sub(/\/$/, "", system_dir)
    # Track whether any -isystem arguments were provided.
    isystem_was_used = 0
    # Allow filtering out specific arguments from the parent script.
    split(ENVIRON["SPACK_arg_filter"], spack_arg_filter, "\n")
}

# Add environment variables used to reconstruct the final command line, but not
# in the main option processing loop.
END {
    spack_command = assert_nonempty(ENVIRON["SPACK_command"], "$SPACK_command")
    spack_mode = assert_nonempty(ENVIRON["SPACK_mode"], "$SPACK_mode")
    # This may legitimately be an empty string.
    spack_lang_flags = ENVIRON["SPACK_lang_flags"]
    spack_add_debug_flags = assert_nonempty(ENVIRON["SPACK_ADD_DEBUG_FLAGS"], "$SPACK_ADD_DEBUG_FLAGS")
    # SPACK_<LANG>FLAGS and SPACK_LDLIBS are split by " "
    split(ENVIRON["SPACK_FFLAGS"], spack_fflags, " ")
    split(ENVIRON["SPACK_CPPFLAGS"], spack_cppflags, " ")
    split(ENVIRON["SPACK_CFLAGS"], spack_cflags, " ")
    split(ENVIRON["SPACK_CXXFLAGS"], spack_cxxflags, " ")
    split(ENVIRON["SPACK_TARGET_ARGS"], spack_target_args, " ")
    split(ENVIRON["SPACK_LDFLAGS"], spack_ldflags, " ")
    spack_short_spec = assert_nonempty(ENVIRON["SPACK_SHORT_SPEC"], "$SPACK_SHORT_SPEC")
    spack_add_rpaths = assert_nonempty(ENVIRON["SPACK_add_rpaths"], "$SPACK_add_rpaths")
    split(ENVIRON["SPACK_RPATH_DIRS"], spack_rpath_dirs, ":")
    split(ENVIRON["SPACK_LINK_DIRS"], spack_link_dirs, ":")
    split(ENVIRON["SPACK_COMPILER_EXTRA_RPATHS"], spack_compiler_extra_rpaths, ":")
    split(ENVIRON["SPACK_COMPILER_IMPLICIT_RPATHS"], spack_compiler_implicit_rpaths, ":")
    split(ENVIRON["SPACK_LDLIBS"], spack_ldlibs, " ")
    split(ENVIRON["SPACK_INCLUDE_DIRS"], spack_include_dirs, ":")
    spack_rpath_arg = assert_nonempty(ENVIRON["SPACK_rpath"], "$SPACK_rpath")
}

function is_system_dir(dir) {
    sub(/\/$/, "", dir)
    for (system_dir in spack_system_dirs) {
        if (dir == spack_system_dirs[system_dir]) {
           return 1
        }
    }
    return 0
}

function array_length(array) {
    k = 0
    for (i in array) { ++k }
    return k
}

function append(array, element) {
    array[array_length(array) + 1] = element
}

function append2(array, element1, element2) {
    append(array, element1)
    append(array, element2)
}

function concatenate(array_base, array_source) {
    for (i in array_source) append(array_base, array_source[i])
}

function add_rpath(rp) {
    if (!rp) return
    if (is_system_dir(rp)) append(system_rpaths, rp)
    else append(rpaths, rp)
}

function error_message(msg) {
    print msg | "cat >&2"
}

function die(msg) {
    error_message(msg)
    exit 1
}

function assert_nonempty(arg, description) {
    if (!arg) {
        die("Argument \"" description "\" was expected to be a non-empty string!")
    }
    return arg
}

function is_filtered_arg(arg) {
    for (i in spack_arg_filter) {
        # If arg_filter[i] occurs as a substring of arg, this succeeds.
        if (index(arg, spack_arg_filter[i])) return 1
    }
    return 0
}

# The behavior of a for loop on an unitialized variable is undefined by POSIX,
# so we can call split() on something that we know will produce an empty array
# to avoid this ambiguity.
function initialize_array(array) {
    split("", array, "")
}

BEGIN {
    initialize_array(isystem_system_includes)
    initialize_array(isystem_includes)
    initialize_array(system_includes)
    initialize_array(includes)
    initialize_array(system_libdirs)
    initialize_array(libdirs)
    initialize_array(other_args)
    initialize_array(system_rpaths)
    initialize_array(rpaths)
}

# Parse the command line arguments.
#
# We extract -L, -I, -isystem and -Wl,-rpath arguments from the
# command line and recombine them with Spack arguments later.  We
# parse these out so that we can make sure that system paths come
# last, that package arguments come first, and that Spack arguments
# are injected properly.
#
# All other arguments, including -l arguments, are treated as
# other_args and left in their original order.  This ensures that
# --start-group, --end-group, and other order-sensitive flags continue to
# work as the caller expects.
function option_processing_loop() {
    # Multiple consecutive spaces in the command line can result in blank
    # arguments, so we remove those. We assume blank arguments are meaningless
    # to any tool we would invoke.
    if (/^$/) return
    if (is_filtered_arg($0)) return

    if (sub(/^-isystem/, "")) {
        isystem_was_used = 1
        if (!$0) getline
        if (is_system_dir($0)) append(isystem_system_includes, $0)
        else append(isystem_includes, $0)
    }
    else if (sub(/^-I/, "")) {
        if (!$0) getline
        if (is_system_dir($0)) append(system_includes, $0)
        else append(includes, $0)
    }
    else if (sub(/^-L/, "")) {
        if (!$0) getline
        if (is_system_dir($0)) append(system_libdirs, $0)
        else append(libdirs, $0)
    }
    else if (sub(/^-l/, "")) {
        if (!$0) getline
        append(other_args, "-l" $0)
    }
    else if (sub(/^-Wl,/, "")) {
        if (!$0) getline
        if (sub(/^-?-rpath[=,]/, "")) add_rpath($0)
        else if (/^-?-rpath$/) {
            getline
            if (sub(/^-Wl,/, "")) add_rpath($0)
            else die("-Wl,-rpath was not followed by -Wl,* (was: " $0 ")")
        }
        else if ($0 == ENVIRON["SPACK_DTAGS_TO_STRIP"]) {
            # Do nothing; we want to remove this flag explicitly.
        }
        else append(other_args, "-Wl," $0)
    }
    else if (sub(/^-Xlinker,/, "")) {
        if (!$0) getline
        if (sub(/^-?-rpath[=,]/, "")) add_rpath($0)
        else if (/^-?-rpath$/) {
            getline
            if (sub(/^-Xlinker,/, "")) add_rpath($0)
            else die("-Xlinker,-rpath was not followed by -Xlinker,* (was: " $0 ")")
        }
        else append(other_args, "-Xlinker," $0)
    }
    else if ($0 == "-Xlinker") {
        getline
        if ($0 == "-rpath") {
            getline
            if ($0 == "-Xlinker") {
                getline
                add_rpath($0)
            }
            else die("-Xlinker -rpath was not followed by -Xlinker (was: " $0 ")")
        }
        else if ($0 == ENVIRON["SPACK_DTAGS_TO_STRIP"]) {
            # Do nothing; we want to remove this flag explicitly.
        }
        else {
            append(other_args, "-Xlinker")
            # If we did not get "-Xlinker -rpath" or
            # "-Xlinker $SPACK_DTAGS_TO_STRIP", then re-run the option
            # processing loop with the current value of $0.
            option_processing_loop()
        }
    }
    else if ($0 == ENVIRON["SPACK_DTAGS_TO_STRIP"]) {
        # Do nothing; we want to remove this flag explicitly.
    }
    else append(other_args, $0)
}

# Execute the main option processing loop, at most once per input record. The
# option processing loop will internally call getline if it needs to advance
# to the next argument before returning.
{ option_processing_loop() }

function is_cc_mode() {
    return (spack_mode ~ /^(cc|ccld)$/)
}

function is_linker_mode() {
    return (spack_mode ~ /^(ld|ccld)$/)
}

function uses_c_preprocessor() {
    return (spack_mode ~ /^(cpp|as|cc|ccld)$/)
}

function is_fortran_lang() {
    return (spack_lang_flags == "F")
}

function is_c_lang() {
    return (spack_lang_flags == "C")
}

function is_cxx_lang() {
    return (spack_lang_flags == "CXX")
}

function is_macos() {
    return (spack_short_spec ~ /darwin/)
}

function should_add_rpaths() {
    return (spack_add_rpaths != "false")
}

END {
    initialize_array(flags)
    initialize_array(args)
    initialize_array(libs)
}

# Add flags from cppflags, cflags, cxxflags, fcflags, fflags, and
# ldflags. We stick to the order that gmake puts the flags in by default.
#
# See the gmake manual on implicit rules for details:
# https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html
END {
    if (is_cc_mode()) {
        concatenate(flags, spack_target_args)
    }

    # Add debug flags.
    if (spack_add_debug_flags == "true") {
        # Add debug flags.
        append(flags, ENVIRON["SPACK_debug_flags"])
    }
    else if (spack_add_debug_flags == "custom") {
        # If a custom flag is requested, derive from environment.
        split(ENVIRON["SPACK_DEBUG_FLAGS"], debug_flags, " ")
        concatenate(flags, debug_flags)
    }

    # Fortran flags come before CPPFLAGS.
    if (is_cc_mode() && is_fortran_lang()) {
        concatenate(flags, spack_fflags)
    }

    # C preprocessor flags come before any C/CXX flags.
    if (uses_c_preprocessor()) {
        concatenate(flags, spack_cppflags)
    }

    # Add C and C++ flags.
    if (is_cc_mode()) {
        if (is_c_lang()) concatenate(flags, spack_cflags)
        else if (is_cxx_lang()) concatenate(flags, spack_cxxflags)
    }

    # Add linker flags.
    if (is_linker_mode()) {
        concatenate(flags, spack_ldflags)
    }

    # On macOS insert headerpad_max_install_names linker flag.
    if (is_macos()) {
        if (spack_mode == "ld") append(flags, "-headerpad_max_install_names")
        else if (spack_mode == "ccld") append(flags, "-Wl,-headerpad_max_install_names")
    }

    # Add RPATHs and lib directories if we are in any linking mode.
    if (is_linker_mode()) {
        # Append RPATH directories. Note that in the case of the top-level
        # package these directories may not exist yet. For dependencies it is
        # assumed that paths have already been confirmed.
        if (should_add_rpaths()) {
            concatenate(rpaths, spack_rpath_dirs)
        }

        concatenate(libdirs, spack_link_dirs)

        # Set extra RPATHs.
        concatenate(libdirs, spack_compiler_extra_rpaths)
        if (should_add_rpaths()) {
            concatenate(rpaths, spack_compiler_extra_rpaths)
            # Set implicit RPATHs.
            concatenate(rpaths, spack_compiler_implicit_rpaths)
        }

        # Add SPACK_LDLIBS to args.
        for (l in spack_ldlibs) {
            sub(/^-l/, "", spack_ldlibs[l])
            append(libs, spack_ldlibs[l])
        }
    }
}

# Finally, reassemble the command line.
END {
    # Add the command name.
    append(args, spack_command)

    # Add the flags assembled earlier.
    concatenate(args, flags)

    # Insert include directories just prior to any system include directories.
    for (i in includes) append(args, "-I" includes[i])
    for (i in isystem_includes) append2(args, "-isystem", isystem_includes[i])

    if (uses_c_preprocessor()) {
        if (isystem_was_used) {
            for (i in spack_include_dirs) append2(args, "-isystem", spack_include_dirs[i])
        }
        else {
            for (i in spack_include_dirs) append(args, "-I" spack_include_dirs[i])
        }
    }

    for (i in system_includes) append(args, "-I" system_includes[i])
    for (i in isystem_system_includes) append2(args, "-isystem", isystem_system_includes[i])

    # Add library search paths.
    for (l in libdirs) append(args, "-L" libdirs[l])
    for (l in system_libdirs) append(args, "-L" system_libdirs[l])

    # Add RPATHs.
    if (spack_mode == "ccld") {
        if (ENVIRON["SPACK_DTAGS_TO_ADD"]) append(args, ENVIRON["SPACK_LINKER_ARG"] ENVIRON["SPACK_DTAGS_TO_ADD"])
        for (r in rpaths) append(args, spack_rpath_arg rpaths[r])
        for (r in system_rpaths) append(args, spack_rpath_arg system_rpaths[r])
    }
    else if (spack_mode == "ld") {
        if (ENVIRON["SPACK_DTAGS_TO_ADD"]) append(args, ENVIRON["SPACK_DTAGS_TO_ADD"])
        for (r in rpaths) append2(args, "-rpath", rpaths[r])
        for (r in system_rpaths) append2(args, "-rpath", system_rpaths[r])
    }

    # Add other arguments from the input command.
    concatenate(args, other_args)

    # Inject SPACK_LDLIBS, if supplied.
    for (l in libs) append(args, "-l" libs[l])
}

# Print out each argument, delimited by newline.
END {
    for (a in args) print(args[a])
}
'

# Set $SPACK_arg_filter to a '\n'-delimited string of entries to use to filter
# out arguments from the awk script used to process arguments. Arguments are
# filtered out if they contain any entry as a substring.
case "$mode" in
    ccld|ld)
        # -loopopt=0 is generated erroneously in autoconf <= 2.69, and passed by
        # ifx to the linker, which confuses it with a library. Filter it out.
        export SPACK_arg_filter='-loopopt'
        ;;
esac

# Pipe through mode variables into the awk script.
export SPACK_command="$command"
export SPACK_mode="$mode"
export SPACK_lang_flags="$lang_flags"
export SPACK_debug_flags="${debug_flags:-}"
export SPACK_add_rpaths="$add_rpaths"
export SPACK_rpath="$rpath"

# The below variables are set in the awk script to ensure we set RPATH instead
# of RUNPATH (or the opposite, depending on the configuration in config.yaml).
#
# Documentation on this mechanism is lacking at best. A few sources
# of information are (note that some of them take explicitly the
# opposite stance that Spack does):
# - http://blog.qt.io/blog/2011/10/28/rpath-and-runpath/
# - https://wiki.debian.org/RpathIssue
#
# The only discussion that could be found on enabling new dynamic tags by
# default on ld is the following:
# - https://sourceware.org/ml/binutils/2013-01/msg00307.html
#
# Variables read by the awk script:
# - $SPACK_DTAGS_TO_ADD
# - $SPACK_DTAGS_TO_STRIP
# - $SPACK_LINKER_ARG

# Execute awk to generate a newline-delimited command string.
# Note: the '-L' flag can be set for gnu awk to warn about behavior undefined by
# POSIX. When editing the complex awk script here, it is recommended to set the
# '-L' flag in this invocation and insert an 'exit 1' after invoking awk, then
# attempt to 'spack install' something (e.g. gnupg) and inspect the config.log
# file after the ./configure script fails to see if e.g. any uninitialized
# arrays were used.
newline_command_string="$(printf '%s\n' "$@" | path_safe_awk "$awk_args_script")"
if [ "$?" -ne 0 ]; then
    exit "$?"
fi

# Prepend the ccache binary if we're using ccache.
if [ -n "${SPACK_CCACHE_BINARY:-}" ]; then
    case "$lang_flags" in
        C|CXX)  # ccache only supports C languages
            newline_command_string="${SPACK_CCACHE_BINARY}\n${newline_command_string}"
            # workaround for stage being a temp folder
            # see #3761#issuecomment-294352232
            export CCACHE_NOHASHDIR=yes
            ;;
    esac
fi

# dump the full command if the caller supplies SPACK_TEST_COMMAND=dump-args
if [ "$SPACK_TEST_COMMAND" = 'dump-args' ]; then
    echo "${newline_command_string}"
    exit
elif [ "${SPACK_TEST_COMMAND#dump-env-}" != "$SPACK_TEST_COMMAND" ]; then
    readonly varname="${SPACK_TEST_COMMAND#dump-env-}"
    eval "echo \"\$0: \$varname: \$$varname\""
elif [ -n "$SPACK_TEST_COMMAND" ]; then
    die "Unknown test command: '$SPACK_TEST_COMMAND'."
fi

readonly spaced_command_string="$(echo "$newline_command_string" | tr '\n' ' ')"

#
# Write the input and output commands to debug logs if it's asked for.
#
if [ "${SPACK_DEBUG:-}" = 'TRUE' ]; then
    input_log="${SPACK_DEBUG_LOG_DIR}/spack-cc-$SPACK_DEBUG_LOG_ID.in.log"
    output_log="${SPACK_DEBUG_LOG_DIR}/spack-cc-$SPACK_DEBUG_LOG_ID.out.log"
    echo "[${mode}] ${command} ${input_command}" >> "$input_log"
    echo "[${mode}] ${spaced_command_string}" >> "$output_log"
fi

exec $spaced_command_string
