files(
    sources=['*.json'],
)

python_library(
    name='lib',
    sources=['**/*.py'],
    dependencies=[
        ':resources',
    ],
)

resources(
    name='resources',
    sources=['*.json'],
)
